apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-dev
  namespace: gitlab-managed-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-dev
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
